#!/bin/bash
pwd
ls -ltr
touch test
ls -ltr
echo "testing" >> test
ls -ltr
echo "$Environment for $Variable" >> test
echo "[Info] GIT JENKINSIntegration demo"
echo "[Info] SCM JENKINSIntegration demo"
echo "[Info] Sesha JENKINSIntegration demo"
